<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fal_securedownload"
 *
 * Auto generated by Extension Builder 18-02-14
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Secure file download',
	'description' => 'Secure file download.',
	'category' => 'plugin',
	'author' => 'Frans Saris',
	'author_email' => 't3ext@beech.it',
	'author_company' => 'Beech.it',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0 - 6.2.999',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>